
const WebsiteInfo = (()=>{
  const MAKES=['Acura','Alfa Romeo','Audi','BMW','Buick','Cadillac','Chevrolet','Chrysler','Dodge','Fiat','Ford','Genesis','GMC','Honda','Hyundai','Infiniti','Jaguar','Jeep','Kia','Land Rover','Lexus','Lincoln','Mazda','Mercedes-Benz','MINI','Mitsubishi','Nissan','Porsche','Ram','Subaru','Tesla','Toyota','Volkswagen','Volvo'];
  const clean=s=>String(s||'').replace(/\r/g,'').replace(/[ \t]+/g,' ').trim();
  const moneyDigits=s=>String(s||'').replace(/[^0-9.]/g,'').replace(/\.00$/,'');
  const priceValue=s=>{const n=Number(String(s||'').replace(/[^0-9.]/g,''));return Number.isFinite(n)&&n>=1000&&n<=500000?Math.round(n):null};
  const CURRENT_PRICE_LABELS=[['your price',125],['sale price',120],['selling price',120],['dealer price',118],['internet price',118],['online price',116],['special price',116],['our price',114],['cash price',112],['current price',110],['price',76]];
  const BAD_PRICE_CONTEXT=/(?:msrp|list price|regular price|was price|market value|savings?|discount|rebate|down payment|bi[- ]?weekly|weekly|monthly|per month|\/mo|finance|lease|payment)/i;
  const CALL_FOR_PRICE_RE=/(?:call|contact|inquire|enquire)(?:\s+(?:us|dealer|sales))?\s+(?:for|about)\s+(?:the\s+)?(?:price|pricing)|(?:price|pricing)\s+(?:on\s+request|available\s+(?:by|on)\s+request)|please\s+call\s+(?:for\s+)?(?:price|pricing)/i;
  function expectedVehicleTokens(v={}){return{stock:String(v.stock||'').trim().toUpperCase(),vin:String(v.vin||'').trim().toUpperCase(),year:String(v.year||'').trim().toUpperCase(),make:String(v.make||'').trim().toUpperCase(),modelTokens:String(v.model||'').toUpperCase().split(/[^A-Z0-9]+/).filter(x=>x.length>1)}}
  function vehicleTextMatchScore(text,v={}){const t=String(text||'').toUpperCase(),e=expectedVehicleTokens(v);let score=0;if(e.vin&&t.includes(e.vin))score+=360;if(e.stock&&t.includes(e.stock))score+=300;if(e.year&&t.includes(e.year))score+=30;if(e.make&&t.includes(e.make))score+=45;if(e.modelTokens.length){const hits=e.modelTokens.filter(x=>t.includes(x)).length;score+=Math.round(90*hits/e.modelTokens.length)}return score}
  function recentRejectedPrices(v={}){const rows=Array.isArray(v?.websitePriceFinding?.feedback)?v.websitePriceFinding.feedback:[],cut=Date.now()-14*86400000;return new Set(rows.filter(x=>(Date.parse(x.at||0)||0)>=cut&&x.reason!=='vehicle-unavailable').map(x=>priceValue(x.detectedPrice)).filter(Boolean))}
  function learnedPriceBonus(expectedVehicle={},candidate={}){const hints=Array.isArray(expectedVehicle?._websitePriceHints)?expectedVehicle._websitePriceHints:[];let bonus=0;for(const h of hints){if(h?.source&&candidate.source&&String(h.source)===String(candidate.source))bonus=Math.max(bonus,12);if(h?.label&&candidate.label&&String(h.label).toLowerCase()===String(candidate.label).toLowerCase())bonus=Math.max(bonus,26);if(h?.reason&&candidate.reason&&String(candidate.reason).toLowerCase().includes(String(h.reason).toLowerCase().slice(0,28)))bonus=Math.max(bonus,18)}return bonus}
  function structuredVehiclePrices(doc,html=''){const out=[];const addObj=(obj,source='jsonld')=>{if(!obj||typeof obj!=='object')return;if(Array.isArray(obj)){obj.forEach(x=>addObj(x,source));return}const offer=Array.isArray(obj.offers)?obj.offers[0]:obj.offers||{},rawPrice=offer?.price??offer?.lowPrice??obj.price??obj.salePrice??obj.currentPrice,price=priceValue(rawPrice);if(price){const brand=typeof obj.brand==='string'?obj.brand:(obj.brand?.name||''),model=typeof obj.model==='string'?obj.model:(obj.model?.name||''),name=[obj.name,obj.headline,obj.vehicleModelDate,brand,model].filter(Boolean).join(' ');out.push({price,source,name,vin:obj.vehicleIdentificationNumber||obj.vin||obj.vehicleIdentificationNumberValue||'',stock:obj.sku||obj.stockNumber||obj.stock||'',url:obj.url||offer?.url||'',availability:offer?.availability||obj.availability||''})}for(const [k,val] of Object.entries(obj)){if(k==='offers')continue;if(val&&typeof val==='object')addObj(val,source)}};for(const el of doc.querySelectorAll('script[type*="ld+json"]')){try{addObj(JSON.parse(el.textContent||''),'jsonld')}catch{}}for(const sel of ['meta[itemprop="price"]','meta[property="product:price:amount"]','meta[property="og:price:amount"]','meta[name="price"]']){for(const el of doc.querySelectorAll(sel)){const price=priceValue(el.getAttribute('content'));if(price)out.push({price,source:'meta',name:doc.title||'',vin:'',stock:'',url:'',availability:''})}}return out}
  function candidateWindows(text,v={}){const raw=String(text||''),upper=raw.toUpperCase(),e=expectedVehicleTokens(v),anchors=[];if(e.vin){let i=upper.indexOf(e.vin);while(i>=0){anchors.push(i);i=upper.indexOf(e.vin,i+1)}}if(e.stock){let i=upper.indexOf(e.stock);while(i>=0){anchors.push(i);i=upper.indexOf(e.stock,i+1)}}if(!anchors.length){const phrase=[e.year,e.make,...e.modelTokens.slice(0,3)].filter(Boolean).join(' ');if(phrase){const i=upper.indexOf(phrase);if(i>=0)anchors.push(i)}}if(!anchors.length)return[{text:raw,offset:0,anchor:false}];return anchors.slice(0,6).map(i=>{const start=Math.max(0,i-1400);return{text:raw.slice(start,Math.min(raw.length,i+1800)),offset:start,anchor:true,anchorAt:i-start}})}
  function priceMatchesVehicleIdentifier(price,v={}){const n=priceValue(price);if(!n)return false;const stockDigits=String(v.stock||'').replace(/\D/g,'');if(stockDigits.length>=4&&stockDigits.length<=7&&Number(stockDigits)===n)return true;return false}
  function detectCallForPrice(text,expectedVehicle={}){for(const win of candidateWindows(text,expectedVehicle)){const m=String(win.text||'').match(CALL_FOR_PRICE_RE);if(!m)continue;const localVehicleScore=vehicleTextMatchScore(win.text,expectedVehicle);if(win.anchor||localVehicleScore>=120)return{found:true,confidence:win.anchor?'high':'suggested',reason:'Original Listing Website explicitly says Call for Price'};}return null}
  function detectVehiclePrice(text,extra={},expectedVehicle={}){const rejected=recentRejectedPrices(expectedVehicle),candidates=[];for(const sv of extra.structuredPrices||[]){let score=135+vehicleTextMatchScore([sv.name,sv.vin,sv.stock,sv.url].join(' '),expectedVehicle);if(sv.vin&&expectedVehicle.vin&&String(sv.vin).toUpperCase()===String(expectedVehicle.vin).toUpperCase())score+=180;if(sv.stock&&expectedVehicle.stock&&String(sv.stock).toUpperCase()===String(expectedVehicle.stock).toUpperCase())score+=150;if(/outofstock|sold|discontinued/i.test(String(sv.availability||'')))score-=80;if(rejected.has(sv.price))score-=95;score+=learnedPriceBonus(expectedVehicle,{source:sv.source,reason:`Structured vehicle price (${sv.source})`});candidates.push({price:sv.price,score,reason:`Structured vehicle price (${sv.source})`,source:sv.source,label:'structured'})}
    for(const win of candidateWindows(text,expectedVehicle)){const local=win.text;for(const [label,base] of CURRENT_PRICE_LABELS){const rx=new RegExp(String.raw`(?:^|\n|\b)${label.replace(/ /g,String.raw`\s+`)}[^$0-9]{0,45}\$?\s*([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{4,7})`,'ig');let m;while((m=rx.exec(local))){const price=priceValue(m[1]);if(!price||priceMatchesVehicleIdentifier(price,expectedVehicle))continue;const around=local.slice(Math.max(0,m.index-90),Math.min(local.length,m.index+m[0].length+100));if(CALL_FOR_PRICE_RE.test(m[0])||CALL_FOR_PRICE_RE.test(around))continue;let score=base+(win.anchor?100:0)+(win.anchor?Math.max(0,90-Math.floor(Math.abs(m.index-(win.anchorAt||0))/12)):0);if(BAD_PRICE_CONTEXT.test(around)&&!/your price|sale price|selling price|dealer price|internet price|online price|special price|our price|cash price/i.test(label))score-=95;if(/discount|savings?|rebate/i.test(around)&&!/price/i.test(label))score-=90;if(rejected.has(price))score-=115;score+=learnedPriceBonus(expectedVehicle,{source:'text',label,reason:`${label} near matched vehicle information`});candidates.push({price,score,reason:`${label} near matched vehicle information`,source:'text',label})}}}
    // Fallback: dollar values near an exact vehicle anchor only. Never trust page-wide random prices.
    for(const win of candidateWindows(text,expectedVehicle).filter(w=>w.anchor)){const rx=/\$\s*([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{4,7})/g;let m;while((m=rx.exec(win.text))){const price=priceValue(m[1]);if(!price||priceMatchesVehicleIdentifier(price,expectedVehicle))continue;const around=win.text.slice(Math.max(0,m.index-100),Math.min(win.text.length,m.index+120));if(CALL_FOR_PRICE_RE.test(around))continue;let score=82+Math.max(0,85-Math.floor(Math.abs(m.index-(win.anchorAt||0))/12));if(BAD_PRICE_CONTEXT.test(around))score-=70;if(rejected.has(price))score-=115;score+=learnedPriceBonus(expectedVehicle,{source:'nearby',label:'nearby',reason:'Price near exact vehicle identifier'});candidates.push({price,score,reason:'Price near exact vehicle identifier',source:'nearby',label:'nearby'})}}
    const grouped=new Map();for(const c of candidates){const prev=grouped.get(c.price);if(!prev||c.score>prev.score)grouped.set(c.price,c)}const sorted=[...grouped.values()].sort((a,b)=>b.score-a.score);if(!sorted.length)return null;const best=sorted[0],second=sorted[1];if(second&&best.score-second.score<18&&best.price!==second.price)return{...best,confidence:'low',ambiguous:true,alternatives:sorted.slice(0,4)};return{...best,confidence:best.score>=180?'high':best.score>=120?'suggested':'low',alternatives:sorted.slice(0,4)}}
  const add=(out,key,value,confidence='high',reason='')=>{value=String(value??'').trim();if(!value)return;const prev=out[key];if(!prev||(prev.confidence!=='high'&&confidence==='high'))out[key]={value,confidence,reason};};
  function urlOk(raw){try{const u=new URL(String(raw||'').trim());if(!/^https?:$/.test(u.protocol))throw 0;return u.href}catch{throw new Error('Enter a complete http:// or https:// vehicle page URL.')}}
  function absoluteUrl(raw,base){try{return new URL(String(raw||'').trim(),base).href}catch{return''}}
  function carfaxReportUrl(raw,base=''){
    const text=String(raw||'').replace(/&amp;/gi,'&').trim();let href='';try{href=/^https?:\/\//i.test(text)?new URL(text).href:absoluteUrl(text,base)}catch{return''}if(!href)return'';
    try{const u=new URL(href),host=u.hostname.toLowerCase();if(host!=='vhr.carfax.ca')return'';if(/\.(?:svg|png|jpe?g|gif|webp|avif|ico|css|js)(?:$|\?)/i.test(u.pathname+u.search))return'';return u.href}catch{return''}
  }
  function extractCarfaxReportUrl(doc,raw,base){
    const links=[...doc.querySelectorAll('a[href]')].map(a=>carfaxReportUrl(a.getAttribute('href'),base)).filter(Boolean);if(links.length)return links[0];
    const cleaned=String(raw||'').replace(/\\u002[fF]/g,'/').replace(/\\\//g,'/').replace(/\\u0026/gi,'&').replace(/\\u003[dD]/g,'=').replace(/&amp;/gi,'&');
    const matches=cleaned.match(/https?:\/\/vhr\.carfax\.ca\/[^\s\"'<>\\]+/ig)||[];for(const m of matches){const good=carfaxReportUrl(m,base);if(good)return good}return'';
  }
  function likelyVehicleImage(url){const u=String(url||'');if(!/^https?:/i.test(u))return false;if(/logo|favicon|icon|sprite|equifax|facebook|instagram|youtube|linkedin|tiktok|avatar|placeholder|badge|carfax|pixel|tracking|staticmap|mapbox|maps?\.google|googleapis\.com\/maps|\/maps?\/|location[-_ ]?(?:map|pin)|directions[-_ ]?map|\.svg(?:\?|$)/i.test(u))return false;return /\.(?:jpe?g|png|webp|avif)(?:\?|$)/i.test(u)||/image|photo|vehicle|inventory|media|cdn/i.test(u)}
  function imageSizeHint(item){const raw=String(item?.url||item||'');let w=+(item?.width||0),h=+(item?.height||0),descriptor=+(item?.descriptorWidth||0);try{const u=new URL(raw);const num=k=>+(u.searchParams.get(k)||0);w=Math.max(w,num('w'),num('width'),num('imwidth'),num('maxWidth'));h=Math.max(h,num('h'),num('height'),num('imheight'),num('maxHeight'));}catch{}const pair=raw.match(/(?:^|[\/_-])(\d{3,4})[xX](\d{3,4})(?=[\/_.?&-]|$)/);if(pair){w=Math.max(w,+pair[1]);h=Math.max(h,+pair[2])}for(const m of raw.matchAll(/(?:^|[?&/_,-])(?:w|width)[=_-]?(\d{3,4})/ig))w=Math.max(w,+m[1]);for(const m of raw.matchAll(/(?:^|[?&/_,-])(?:h|height)[=_-]?(\d{3,4})/ig))h=Math.max(h,+m[1]);w=Math.max(w,descriptor);return{w,h}}
  function canonicalImageKey(raw){try{const u=new URL(String(raw||''));['w','width','h','height','imwidth','imheight','maxWidth','maxHeight','q','quality','dpr','fit','crop','auto','format','fm'].forEach(k=>u.searchParams.delete(k));u.hash='';u.pathname=u.pathname.replace(/\/(?:tr:)?(?:w|h)[-_]\d{2,4}(?:[,x_-](?:w|h)?[-_]?\d{2,4})*\//ig,'/').replace(/([_-])\d{3,4}[xX]\d{3,4}(?=([_.-]|$))/g,'$1SIZE');const qs=[...u.searchParams.entries()].sort().map(([k,v])=>`${k}=${v}`).join('&');return `${u.origin}${u.pathname}${qs?'?'+qs:''}`.toLowerCase()}catch{return String(raw||'').replace(/([?&](?:w|width|h|height|quality|q)=[^&]*)/gi,'').toLowerCase()}}
  function imageScore(item){const {w,h}=imageSizeHint(item);let score=(w&&h?w*h:Math.max(w,h)*1000);const u=String(item?.url||item||'');if(/original|full|large|xl|high[-_]?res|master/i.test(u))score+=500000;if(/thumb|thumbnail|small|tiny|preview|low[-_]?res/i.test(u))score-=500000;return score}
  function uniqueImages(list){const best=new Map(),order=[];for(const rawItem of list){const item=typeof rawItem==='string'?{url:rawItem}:rawItem||{};const url=String(item.url||'').trim(),name=String(item.name||'');if(!likelyVehicleImage(url)||item.region==='related')continue;if(/(?:^|\b)(?:map|location|directions|dealership location|store location)(?:\b|$)/i.test(name))continue;const key=canonicalImageKey(url);const candidate={url,name:item.name||'',width:+item.width||0,height:+item.height||0,descriptorWidth:+item.descriptorWidth||0,position:Number.isFinite(+item.position)?+item.position:.5,sourceIndex:+item.sourceIndex||0,region:item.region||'primary'};if(!best.has(key)){best.set(key,candidate);order.push(key)}else{const prev=best.get(key),primaryBonus=x=>x.region==='primary'?1000000000000:0;if(primaryBonus(candidate)+imageScore(candidate)>primaryBonus(prev)+imageScore(prev))best.set(key,candidate)}}const out=[];for(const key of order){const x=best.get(key),{w,h}=imageSizeHint(x);if((w&&h&&w<260&&h<200)||(/thumb|thumbnail|tiny/i.test(x.url)&&Math.max(w,h)&&Math.max(w,h)<500))continue;out.push(x);if(out.length>=100)break}return out.sort((a,b)=>(a.position??.5)-(b.position??.5)||(a.sourceIndex||0)-(b.sourceIndex||0))}
  function probeImage(item,timeoutMs=5000){return new Promise(resolve=>{const hinted=imageSizeHint(item);let done=false;const finish=(w=0,h=0)=>{if(done)return;done=true;clearTimeout(timer);resolve({...item,naturalWidth:+w||hinted.w||0,naturalHeight:+h||hinted.h||0})};const img=new Image();img.decoding='async';img.referrerPolicy='no-referrer';img.onload=()=>finish(img.naturalWidth,img.naturalHeight);img.onerror=()=>finish();const timer=setTimeout(()=>finish(),timeoutMs);img.src=item.url})}
  async function probeImages(items,onProgress=()=>{}){const out=new Array(items.length);let next=0,done=0;const worker=async()=>{while(true){const i=next++;if(i>=items.length)return;out[i]=await probeImage(items[i]);done++;if(done===items.length||done%6===0)onProgress(`Checking gallery image sizes… ${done}/${items.length}`)}};await Promise.all(Array.from({length:Math.min(8,Math.max(1,items.length))},worker));return out}
  function photoDimensions(item){const w=+(item.naturalWidth||0)||imageSizeHint(item).w,h=+(item.naturalHeight||0)||imageSizeHint(item).h;return{w,h,area:w*h,ratio:w&&h?w/h:0}}
  function plausiblePhoto(item){const {w,h,area,ratio}=photoDimensions(item),u=String(item.url||''),name=String(item.name||'');if(item.region==='related'||/logo|favicon|icon|sprite|badge|carfax|pixel|tracking|staticmap|mapbox|maps?\.google|googleapis\.com\/maps|location|directions/i.test(u+' '+name))return false;if(w&&h){if(w<420||h<260||area<180000)return false;if(ratio>3.1||ratio<.48)return false;if(ratio>.82&&ratio<1.18&&!/vehicle|inventory|gallery|photo|media/i.test(u))return false}return true}
  function hashDistance(a,b){if(!a||!b||a.length!==b.length)return 999;let d=0;for(let i=0;i<a.length;i++)if(a[i]!==b[i])d++;return d}
  async function visualFingerprint(item){const {area}=photoDimensions(item);if(area<350000)return'';try{const proxy='https://images.weserv.nl/?url='+encodeURIComponent(item.url)+'&w=72&h=72&fit=cover&output=jpg&q=45';const r=await fetch(proxy,{cache:'force-cache'});if(!r.ok)return'';const b=await r.blob();const bmp=await createImageBitmap(b);const c=document.createElement('canvas');c.width=9;c.height=8;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(bmp,0,0,9,8);bmp.close?.();const d=x.getImageData(0,0,9,8).data,g=[];for(let i=0;i<d.length;i+=4)g.push(Math.round(.299*d[i]+.587*d[i+1]+.114*d[i+2]));let bits='';for(let y=0;y<8;y++)for(let col=0;col<8;col++)bits+=g[y*9+col]>g[y*9+col+1]?'1':'0';return bits}catch{return''}}
  async function fingerprintPhotos(items,onProgress=()=>{}){const arr=[...(items||[])];let next=0,done=0;const worker=async()=>{while(true){const i=next++;if(i>=arr.length)return;arr[i]={...arr[i],fingerprint:await visualFingerprint(arr[i])};done++;if(done===arr.length||done%8===0)onProgress(`Comparing duplicate vehicle photos… ${done}/${arr.length}`)}};await Promise.all(Array.from({length:Math.min(6,Math.max(1,arr.length))},worker));return arr}
  function dedupeVisual(photos){const kept=[];for(const p of photos){let hit=-1;for(let i=0;i<kept.length;i++){const k=kept[i];if(p.fingerprint&&k.fingerprint&&hashDistance(p.fingerprint,k.fingerprint)<=3){hit=i;break}}if(hit<0){kept.push(p);continue}const old=kept[hit],pd=photoDimensions(p),od=photoDimensions(old);if(pd.area>od.area*1.02||(Math.abs(pd.area-od.area)<=Math.max(1,od.area*.02)&&(p.position??1)<(old.position??1)))kept[hit]=p}return kept}
  function parallelLowerResGroups(photos){const groups=new Map();for(const p of photos){if(!p.w||!p.h)continue;const key=`${p.w}x${p.h}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p)}const entries=[...groups.entries()].map(([key,group])=>({key,group,count:group.length,area:group[0].area,ratio:group[0].ratio,orders:group.map(x=>x._order).sort((a,b)=>a-b)})).filter(g=>g.count>=3);const suppress=new Set();for(let i=0;i<entries.length;i++)for(let j=i+1;j<entries.length;j++){const a=entries[i],b=entries[j],countRatio=Math.min(a.count,b.count)/Math.max(a.count,b.count);if(countRatio<.82||Math.abs(a.ratio-b.ratio)>.28)continue;const n=Math.min(a.orders.length,b.orders.length),avg=n?a.orders.slice(0,n).reduce((sum,x,k)=>sum+Math.abs(x-b.orders[k]),0)/n:99;if(avg>3.5)continue;const hi=a.area>=b.area?a:b,lo=hi===a?b:a;if(hi.area>lo.area*1.05)suppress.add(lo.key)}return suppress}
  function classifyPhotos(items){let photos=(items||[]).filter(plausiblePhoto).map((x,i)=>({...x,_order:i,...photoDimensions(x)}));photos=dedupeVisual(photos).map((x,i)=>({...x,_order:i}));const suppress=parallelLowerResGroups(photos);photos=photos.filter(p=>!suppress.has(`${p.w}x${p.h}`));const groups=new Map();for(const p of photos){if(!p.w||!p.h)continue;const key=`${p.w}x${p.h}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(p)}const eligible=[...groups.entries()].map(([key,group])=>{const p=group[0],large=p.w>=800&&p.h>=500&&p.area>=500000&&p.ratio>=.9&&p.ratio<=2.35,avgPosition=group.reduce((a,x)=>a+(Number.isFinite(+x.position)?+x.position:.5),0)/group.length;return{key,group,count:group.length,area:p.area,large,avgPosition}}).filter(g=>g.large&&g.count>=2&&g.avgPosition<.78).sort((a,b)=>b.area-a.area||a.avgPosition-b.avgPosition||b.count-a.count);const recommendedKey=eligible[0]?.key||'';const result=[];for(const p of photos){const key=p.w&&p.h?`${p.w}x${p.h}`:'';let confidence='review',reason='Possible vehicle image — review before importing';if(recommendedKey&&key===recommendedKey){confidence='high';reason=`High confidence primary gallery · ${groups.get(key)?.length||0} images at ${key}`}else if(key&&groups.get(key)?.length>=2&&p.w>=800&&p.h>=500){reason=`High-resolution alternate gallery · ${groups.get(key).length} images at ${key}`}else if(p.w&&p.h){reason=`High-resolution image · ${key}`}result.push({...p,confidence,reason,selected:confidence==='high'})}return result.sort((a,b)=>a._order-b._order)}
  const RELATED_SECTION_RE=/^(?:explore more vehicles|similar vehicles|recently viewed|you may also like|recommended vehicles|more vehicles|other vehicles|vehicles you may like)\b/i;
  function extractImagesFromHtml(doc,html,base){const arr=[],imgs=[...doc.querySelectorAll('img')],heads=[...doc.querySelectorAll('h1,h2,h3,h4,h5,h6,[role=heading]')];const relatedHead=heads.find(el=>{const t=clean(el.textContent||'');return t.length<90&&RELATED_SECTION_RE.test(t)});imgs.forEach((img,imgIndex)=>{const w=+(img.getAttribute('width')||0),h=+(img.getAttribute('height')||0),name=img.getAttribute('alt')||'',afterRelated=!!(relatedHead&&(relatedHead.compareDocumentPosition(img)&Node.DOCUMENT_POSITION_FOLLOWING)),position=imgs.length?imgIndex/Math.max(1,imgs.length-1):.5,region=afterRelated?'related':'primary';for(const attr of ['src','data-src','data-lazy-src','data-original']){const u=absoluteUrl(img.getAttribute(attr),base);if(u)arr.push({url:u,name,width:w,height:h,position,sourceIndex:imgIndex,region})}const ss=img.getAttribute('srcset')||img.getAttribute('data-srcset')||'';for(const bit of ss.split(',')){const parts=bit.trim().split(/\s+/),u=absoluteUrl(parts[0],base);if(!u)continue;const dw=/^(\d+)w$/i.test(parts[1]||'')?+(parts[1].match(/\d+/)||[0])[0]:0;arr.push({url:u,name,width:w,height:h,descriptorWidth:dw,position,sourceIndex:imgIndex,region})}});const relatedHtmlPos=html.search(/(?:Explore more vehicles|Similar vehicles|Recently viewed|You may also like|Recommended vehicles|Other vehicles)/i),rx=/(https?:\\?\/\\?\/[^"'\s<>]+?\.(?:jpe?g|png|webp|avif)(?:\?[^"'\s<>\\]*)?)/ig;let m,rawIndex=0;while((m=rx.exec(html))){const region=relatedHtmlPos>=0&&m.index>relatedHtmlPos?'related':'primary';arr.push({url:m[1].replace(/\\\//g,'/').replace(/\\u0026/g,'&'),position:m.index/Math.max(1,html.length),sourceIndex:imgs.length+(rawIndex++),region})}return uniqueImages(arr)}
  function extractImagesFromMarkdown(text,base){const arr=[];let m,idx=0;const relatedMatch=text.match(/(?:^|\n)#{0,6}\s*(?:Explore more vehicles|Similar vehicles|Recently viewed|You may also like|Recommended vehicles|More vehicles|Other vehicles|Vehicles you may like)\b/i),relatedPos=relatedMatch?text.indexOf(relatedMatch[0]):-1;const addMatch=(url,pos)=>arr.push({url:absoluteUrl(url,base),position:pos/Math.max(1,text.length),sourceIndex:idx++,region:relatedPos>=0&&pos>relatedPos?'related':'primary'});const md=/!\[[^\]]*\]\((https?:\/\/[^)\s]+)[^)]*\)/ig;while((m=md.exec(text)))addMatch(m[1],m.index);const raw=/(https?:\/\/[^\s)\]"'<>]+\.(?:jpe?g|png|webp|avif)(?:\?[^\s)\]"'<>]*)?)/ig;while((m=raw.exec(text)))addMatch(m[1],m.index);return uniqueImages(arr)}
  function section(text,heading){const rx=new RegExp('(?:^|\\n)#{1,6}\\s*'+heading+'\\s*\\n([\\s\\S]*?)(?=\\n#{1,6}\\s|$)','i'),m=text.match(rx);return m?clean(m[1].replace(/\[[^\]]+\]\([^)]*\)/g,'').replace(/[*_#]+/g,'')):''}
  function escapeRx(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
  function headingVehicle(text,title=''){const makeOrder=[...MAKES].sort((a,b)=>b.length-a.length);const sources=[...String(text||'').split(/\n+/),String(title||'').replace(/\s*[|–—]\s*.*$/,'')];for(let line of sources){line=clean(line).replace(/^#{1,6}\s*/,'').replace(/^Title:\s*/i,'');const y=line.match(/^((?:19|20)\d{2})\s+(.+)$/);if(!y)continue;const rest=clean(y[2]);for(const mk of makeOrder){const rx=new RegExp('^'+escapeRx(mk)+'(?:\\s+|$)','i');if(!rx.test(rest))continue;let model=clean(rest.replace(rx,''));model=model.replace(/\s*[|–—]\s+.*$/,'').replace(/\s+(?:for sale|used vehicle|pre-owned)\b.*$/i,'').trim();if(!model||/^(?:JUST ARRIVED!?|AVAILABLE|PRICE|FINANCE|CONTACT|BOOK)$/i.test(model))continue;return{year:y[1],make:mk,model}}}return null}
  function parseText(text,url,extra={},expectedVehicle={}){const out={};text=String(text||'');const plain=clean(text);add(out,'originalListingUrl',url,'high','Exact page supplied by user');
    const callForPrice=detectCallForPrice(text,expectedVehicle);if(callForPrice){out.priceStatus={value:'call-for-price',confidence:callForPrice.confidence,reason:callForPrice.reason};}else{const detectedPrice=detectVehiclePrice(text,extra,expectedVehicle);if(detectedPrice){add(out,'price',String(detectedPrice.price),detectedPrice.confidence,detectedPrice.reason);Object.assign(out.price,{ambiguous:detectedPrice.ambiguous===true,source:detectedPrice.source||'',label:detectedPrice.label||'',score:Number(detectedPrice.score)||0,alternatives:(detectedPrice.alternatives||[]).slice(0,4).map(x=>({price:x.price,score:x.score,reason:x.reason,source:x.source,label:x.label||''}))});}}
    const structuredMatch=[...(extra.structuredPrices||[])].map(x=>({x,score:vehicleTextMatchScore([x.name,x.vin,x.stock,x.url].join(' '),expectedVehicle)})).sort((a,b)=>b.score-a.score)[0];if(structuredMatch?.score>=250){if(structuredMatch.x.stock)add(out,'stock',String(structuredMatch.x.stock).toUpperCase(),'high','Stock number from matching structured vehicle data');if(structuredMatch.x.vin)add(out,'vin',String(structuredMatch.x.vin).toUpperCase(),'high','VIN from matching structured vehicle data');}
    let m;
    m=text.match(/(?:STK|STOCK)(?:\s*(?:#|NO\.?|NUMBER))?\s*[:#-]?\s*([A-Z0-9-]{3,20})/i);if(m)add(out,'stock',m[1].toUpperCase(),'high','Stock number on supplied page');
    const vins=text.toUpperCase().match(/\b[A-HJ-NPR-Z0-9]{17}\b/g)||[];if(vins.length)add(out,'vin',vins[0],'high','VIN on supplied page');
    m=text.match(/(?:Kilometers|Kilometres|Odometer|Mileage)\s*\n?\s*([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{3,7})\s*(km|kms|mi|miles)?/i);if(!m)m=text.match(/\b([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{4,7})\s*(km|kms|mi|miles)\b/i);if(m){add(out,'odometer',m[1].replace(/,/g,''),'high','Odometer on supplied page');add(out,'odometerUnit',/^mi/i.test(m[2]||'km')?'MI':'KM','high','Odometer unit on supplied page');}
    const heading=headingVehicle(text,extra.title);if(heading){add(out,'year',heading.year,'high','Year / Make / Model from the same vehicle heading line');add(out,'make',heading.make,'high','Year / Make / Model from the same vehicle heading line');add(out,'model',heading.model,'high','Year / Make / Model from the same vehicle heading line');}
    let desc=extra.description||section(text,'Vehicle details')||section(text,'Description');if(desc){desc=desc.replace(/View more.*$/i,'').trim();if(desc.length>40)add(out,'description',desc.slice(0,5000),'high','Vehicle description on supplied page');}
    const verifiedCarfax=carfaxReportUrl(extra.carfaxUrl,url);if(verifiedCarfax)add(out,'carfaxUrl',verifiedCarfax,'high','CARFAX vehicle-history report link on supplied page');return out;}
  async function fetchWithTimeout(url,options={},timeoutMs=8000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{return await fetch(url,{...options,signal:controller.signal})}finally{clearTimeout(timer)}}
  async function direct(url){const r=await fetchWithTimeout(url,{cache:'no-store',credentials:'omit'},7000);if(!r.ok)throw new Error(`Website returned ${r.status}`);const html=await r.text();const doc=new DOMParser().parseFromString(html,'text/html');const text=doc.body?.innerText||doc.documentElement?.innerText||html;const title=doc.title||'';const meta=doc.querySelector('meta[name="description"]')?.content||'';const carfax=extractCarfaxReportUrl(doc,html,url);return{mode:'direct',text,raw:html,title,description:meta,carfaxUrl:carfax,structuredPrices:structuredVehiclePrices(doc,html),images:extractImagesFromHtml(doc,html,url)};}
  async function reader(url){const relay='https://r.jina.ai/'+url;const r=await fetchWithTimeout(relay,{cache:'no-store',headers:{'Accept':'text/plain'}},9000);if(!r.ok)throw new Error(`Website reader returned ${r.status}`);const text=await r.text();const title=(text.match(/^Title:\s*(.+)$/mi)||[])[1]||'';const cleaned=text.replace(/&amp;/gi,'&').replace(/\\u002[fF]/g,'/').replace(/\\\//g,'/').replace(/\\u0026/gi,'&').replace(/\\u003[dD]/g,'=');const candidates=cleaned.match(/https?:\/\/vhr\.carfax\.ca\/[^\s)\]"'<>]+/ig)||[];const carfax=candidates.map(x=>carfaxReportUrl(x,url)).find(Boolean)||'';return{mode:'reader',text,raw:text,title,description:section(text,'Vehicle details'),carfaxUrl:carfax,images:extractImagesFromMarkdown(text,url)};}
  async function scan(rawUrl,onProgress=()=>{},expectedVehicle={}){const url=urlOk(rawUrl);onProgress('Reading the exact vehicle page…');let src;try{src=await direct(url)}catch(e){onProgress('The dealership blocks direct browser reading — using the same URL through a read-only page fetch helper…');src=await reader(url)}onProgress('Finding vehicle information and photos…');const probed=await probeImages(src.images||[],onProgress);const fingerprinted=await fingerprintPhotos(probed.filter(plausiblePhoto),onProgress);const photos=classifyPhotos(fingerprinted);return{url,mode:src.mode,fields:parseText(src.text,url,src,expectedVehicle),photos,rawText:src.text};}
  async function scanFacts(rawUrl,onProgress=()=>{},expectedVehicle={}){const url=urlOk(rawUrl);onProgress('Reading the exact vehicle page…');let src;try{src=await direct(url)}catch(e){onProgress('Using the exact URL through the read-only page helper…');src=await reader(url)}return{url,mode:src.mode,fields:parseText(src.text,url,src,expectedVehicle),rawText:src.text};}
  async function imageBlob(url){try{const r=await fetch(url,{cache:'no-store'});if(r.ok){const b=await r.blob();if(b.type.startsWith('image/'))return b}}catch{}
    const proxy='https://images.weserv.nl/?url='+encodeURIComponent(url)+'&output=jpg';const r=await fetch(proxy,{cache:'no-store'});if(!r.ok)throw new Error('Photo download blocked');const b=await r.blob();if(!b.type.startsWith('image/'))throw new Error('Not an image');return b;}
  return{scan,scanFacts,imageBlob};
})();
