
const DescriptionTemplates = (()=>{
  const BLOCK_LABELS={headline:'Headline',details:'Vehicle Details',overview:'Overview',features:'Key Features / Highlights',topFeatures:'Top Five Special Features',price:'Price',financing:'Financing',signature:'Dealer / Salesperson Signature',custom:'Custom Text'};
  const defaultBlock=(type,overrides={})=>({id:`BLK-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`,type,enabled:true,useEmojis:true,title:BLOCK_LABELS[type]||'Section',config:{},...overrides});
  const quick={id:'builtin-marketplace-quick',name:'Marketplace - Quick',builtIn:true,description:'Short Marketplace description with the essentials.',blocks:[
    defaultBlock('headline',{id:'quick-headline',useEmojis:false,config:{pattern:'{{YEAR}} {{MAKE}} {{MODEL}} | {{ODOMETER}} | {{CLASS}}'}}),
    defaultBlock('overview',{id:'quick-overview',title:'Overview',config:{sentences:2,guidance:'Keep this concise and focus on the strongest buyer benefits.'}}),
    defaultBlock('features',{id:'quick-features',title:'Key Features',config:{limit:10}}),
    defaultBlock('price',{id:'quick-price',title:'PRICE',config:{text:'{{PRICE}} + GST'}}),
    defaultBlock('signature',{id:'quick-signature',useEmojis:false,title:'Signature',config:{text:'Proudly offered by an AMVIC Licensed Dealer.\nMessage {{USER_NAME}} to set up a viewing or to book.'}})
  ]};
  const detailed={id:'builtin-marketplace-detailed',name:'Marketplace - Detailed',builtIn:true,description:'Detailed Marketplace layout with facts, features, price and financing.',blocks:[
    defaultBlock('headline',{id:'detail-headline',useEmojis:false,config:{pattern:'{{YEAR}} {{MAKE}} {{MODEL}} | {{ENGINE_HP}} | {{ODOMETER}} | {{CLASS}}'}}),
    defaultBlock('details',{id:'detail-details',title:'Vehicle Details',config:{fields:['year','makeModel','drivetrain','odometer','vin','stock']}}),
    defaultBlock('overview',{id:'detail-overview',title:'Overview',config:{sentences:3,guidance:'Use the original vehicle description and verified facts. Focus on strengths without inventing equipment.'}}),
    defaultBlock('features',{id:'detail-features',title:'Key Features / Highlights',config:{limit:30}}),
    defaultBlock('topFeatures',{id:'detail-top',title:'Top Five Special Features',config:{count:5}}),
    defaultBlock('price',{id:'detail-price',title:'PRICE',config:{text:'{{PRICE}} + Personalization + GST'}}),
    defaultBlock('financing',{id:'detail-finance',title:'Financing',config:{text:'Flexible financing options\nOAC (On Approved Credit)\nExtended warranty options available'}}),
    defaultBlock('signature',{id:'detail-signature',useEmojis:false,title:'Signature',config:{text:'Proudly offered by an AMVIC Licensed Dealer.\n🏁 Message {{USER_NAME}} to set up a viewing or to book'}})
  ]};
  const builtins=[quick,detailed];
  async function custom(){return (await DB.get('settings','descriptionTemplates'))?.value||[]}
  async function all(){return [...builtins.map(x=>structuredClone(x)),...(await custom()).map(x=>structuredClone(x))]}
  async function get(id){return (await all()).find(x=>x.id===id)||structuredClone(detailed)}
  async function save(template){const rows=await custom(),idx=rows.findIndex(x=>x.id===template.id);const clean=structuredClone({...template,builtIn:false,updatedAt:Date.now()});if(idx>=0)rows[idx]=clean;else rows.push(clean);await DB.put('settings',{id:'descriptionTemplates',value:rows});return clean}
  async function remove(id){const rows=(await custom()).filter(x=>x.id!==id);await DB.put('settings',{id:'descriptionTemplates',value:rows})}
  function cloneForUser(template){const t=structuredClone(template);t.id=`TPL-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;t.builtIn=false;t.name=template?.builtIn?`${template.name} - My Copy`:(template?.name||'My Marketplace Template');t.blocks=(t.blocks||[]).map(b=>({...b,id:`BLK-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}));return t}
  return{BLOCK_LABELS,defaultBlock,all,get,save,remove,cloneForUser,builtins};
})();

const DescriptionTools = (()=>{
  const norm=s=>String(s||'').replace(/\r/g,'').replace(/[ \t]+/g,' ').trim();
  const money=n=>n!==''&&n!=null&&!Number.isNaN(+n)?new Intl.NumberFormat('en-CA',{style:'currency',currency:'CAD',maximumFractionDigits:0}).format(+n):'';
  const odo=(n,u='KM')=>n!==''&&n!=null&&!Number.isNaN(+n)?`${Number(n).toLocaleString('en-CA')} ${String(u||'KM').toUpperCase()}`:'';
  function first(text,patterns){for(const rx of patterns){const m=String(text||'').match(rx);if(m)return norm(m[1]||m[0])}return''}
  function detectClass(text,model=''){const s=`${model} ${text}`;const phrases=[/\b(Premium Luxury SUV)\b/i,/\b(Luxury SUV)\b/i,/\b(Compact SUV)\b/i,/\b(Midsize SUV)\b/i,/\b(Full[- ]Size SUV)\b/i,/\b(Sports Sedan)\b/i,/\b(Luxury Sedan)\b/i,/\b(Pickup Truck)\b/i,/\b(Crew Cab Pickup)\b/i];for(const rx of phrases){const m=s.match(rx);if(m)return m[1].replace(/\b\w/g,x=>x.toUpperCase())}for(const [rx,label] of [[/\bSUV\b/i,'SUV'],[/\b(?:pickup|truck|crew cab)\b/i,'Pickup Truck'],[/\bsedan\b/i,'Sedan'],[/\bcoupe\b/i,'Coupe'],[/\bhatchback\b/i,'Hatchback'],[/\bwagon\b/i,'Wagon'],[/\bconvertible\b/i,'Convertible'],[/\bminivan\b/i,'Minivan'],[/\bvan\b/i,'Van']])if(rx.test(s))return label;return'Vehicle'}
  const FEATURE_RULES=[
    ['Panoramic Sunroof',/panoramic (?:moonroof|sunroof)|panorama roof/i,100],['Sunroof',/\bsunroof\b|\bmoonroof\b/i,64],['Ventilated Front Seats',/ventilated (?:front )?seats|cooled (?:front )?seats/i,92],['Heated Front Seats',/heated (?:front )?(?:seat|seats|bucket seats)/i,74],['Heated Rear Seats',/heated (?:rear|second[- ]row) seats/i,82],['Heated Steering Wheel',/heated (?:steering )?wheel/i,76],['Remote Engine Start',/remote (?:engine )?start/i,73],['Keyless Start',/keyless (?:start|ignition)|push[- ]button start/i,55],['Kick-Activated Liftgate',/kick[- ]activated liftgate|hands[- ]free liftgate/i,93],['Power Liftgate',/power liftgate|power tailgate/i,72],['Navigation',/navigation (?:system)?|integrated navigation/i,72],['Apple CarPlay',/apple carplay/i,61],['Android Auto',/android auto/i,61],['Bluetooth Connectivity',/bluetooth/i,42],['Automatic Parking',/automatic parking|park assist/i,88],['Adaptive Cruise Control',/adaptive cruise/i,91],['Blind Spot Monitoring',/blind[- ]spot (?:monitoring|monitor|warning)/i,86],['Lane Keeping Assist',/lane[- ]keep|lane keeping|lane departure/i,78],['Forward Collision Mitigation',/forward collision|collision mitigation|automatic emergency braking/i,82],['Backup Camera',/backup camera|rear[- ]view camera|rearview camera/i,58],['Front & Rear Parking Sensors',/(?:front.{0,18}rear|rear.{0,18}front).{0,24}parking sensors|parking sensors/i,67],['Multi-Zone Climate Control',/multi[- ]zone (?:a\/?c|climate)|tri[- ]zone|three[- ]zone/i,69],['Dual-Zone Climate Control',/dual[- ]zone (?:a\/?c|climate)/i,59],['Rain-Sensing Wipers',/rain[- ]sensing wipers/i,62],['Hill Descent Control',/hill descent/i,55],['Premium Audio System',/bose|burmester|harman kardon|mark levinson|klipsch|premium audio/i,79],['360° Camera',/360.{0,8}(?:camera|view)|around view monitor/i,84],['Head-Up Display',/head[- ]up display|heads[- ]up display/i,85],['Wireless Phone Charging',/wireless (?:phone )?charg/i,66],['Memory Driver Seat',/memory (?:driver|front) seat/i,53],['Power Adjustable Front Seats',/power[- ]adjustable (?:front )?seats|power front seats/i,54],['Premium Leather Seating',/leather (?:seat|seats|seating)|ARTICO/i,50],['48V Mild-Hybrid Technology',/48V|mild[- ]hybrid|e[- ]?torque/i,96]
  ];
  function features(text){const found=[];for(const [label,rx,rank] of FEATURE_RULES)if(rx.test(text))found.push({label,rank,confidence:'high',source:'Website / Profile description'});const wheel=String(text||'').match(/\b(1[7-9]|2[0-4])(?:[- ]?inch|\")\s+(?:[A-Za-z-]+\s+){0,3}(?:alloy )?wheels?/i);if(wheel)found.push({label:`${wheel[1]}\" Wheels`,rank:68,confidence:'high',source:'Website'});return [...new Map(found.map(x=>[x.label.toLowerCase(),x])).values()]}
  function parseSupplementary(rawText='',vehicle={}){const text=String(rawText||'');const engine=first(text,[/(?:^|\n)\s*Engine\s*(?:\n|:)\s*([^\n]{2,80})/i,/\b(\d\.\d\s*L\s+(?:I\d|V\d|Inline[- ]?\d|[3468]-Cylinder)[^\n,.]{0,55})/i]);const hp=first(text,[/(?:^|\n)\s*Horsepower\s*(?:\n|:)\s*(\d{2,4}\s*HP)/i,/\b(\d{2,4}\s*HP)\b/i]);const drivetrain=first(text,[/(?:^|\n)\s*Drivetrain\s*(?:\n|:)\s*([^\n]{2,35})/i,/\b(4MATIC|xDrive|quattro|AWD|4WD|FWD|RWD)\b/i]);const transmission=first(text,[/(?:^|\n)\s*Transmission\s*(?:\n|:)\s*([^\n]{2,60})/i,/\b(\d{1,2}[- ]Speed\s+(?:Automatic|Manual|DCT|CVT))\b/i]);const vehicleClass=detectClass(text,vehicle.model||'');return{engine,hp,drivetrain,transmission,vehicleClass,features:features(`${text}\n${vehicle.description||''}`)}}
  function makeModelLabel(make,model){make=norm(make);model=norm(model);if(make&&model.toLowerCase().startsWith(make.toLowerCase()+' '))return model;return [make,model].filter(Boolean).join(' ')}
  function conciseOverview(source,facts,sentences=3){let txt=norm(source||'').replace(/\s+/g,' ');if(txt){txt=txt.replace(/^(?:\d{4}\s+[^.!?]{0,100}[.!?-]\s*)/,'');const parts=txt.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[];const useful=parts.map(norm).filter(x=>x.length>30&&!/call us|contact us|book a test drive|visit .*today/i.test(x)).slice(0,Math.max(1,+sentences||3));if(useful.length)return useful.join(' ')}const bits=[];if(facts.odometer)bits.push(`with ${facts.odometer}`);if(facts.engineHp)bits.push(`powered by ${facts.engineHp}`);if(facts.drivetrain)bits.push(`${facts.drivetrain} capability`);const name=[facts.year,makeModelLabel(facts.make,facts.model)].filter(Boolean).join(' ');return `${name||'This vehicle'} is a well-equipped option ${bits.length?bits.join(', '):'with a strong mix of comfort, technology and everyday usability'}. Review the confirmed features below for the equipment included on this vehicle.`}
  function topFeatures(facts,approvedFeatures,count=5){const out=[];if(facts.odometerValue!==''&&Number(facts.odometerValue)<50000)out.push({label:`Only ${facts.odometer}`,rank:120});if(facts.hp)out.push({label:facts.engine?`${facts.hp} ${facts.engine}`:facts.hp,rank:112});if(facts.drivetrain&&/AWD|4WD|4MATIC|xDrive|quattro/i.test(facts.drivetrain))out.push({label:facts.drivetrain,rank:106});for(const f of approvedFeatures)out.push(f);return [...new Map(out.sort((a,b)=>(b.rank||0)-(a.rank||0)).map(x=>[x.label.toLowerCase(),x])).values()].slice(0,Math.max(1,+count||5))}
  function replaceVars(text,facts,userName){const make=norm(facts.make),rawModel=norm(facts.model),model=make&&rawModel.toLowerCase().startsWith(make.toLowerCase()+' ')?rawModel.slice(make.length).trim():rawModel;const vars={YEAR:facts.year,MAKE:make,MODEL:model,MAKE_MODEL:makeModelLabel(make,rawModel),ENGINE:facts.engine,HP:facts.hp,ENGINE_HP:facts.engineHp,ODOMETER:facts.odometer,CLASS:facts.vehicleClass,DRIVETRAIN:facts.drivetrain,TRANSMISSION:facts.transmission,VIN:facts.vin,STOCK:facts.stock,PRICE:facts.price,USER_NAME:userName||'Salesperson'};return String(text||'').replace(/\{\{([A-Z_]+)\}\}/g,(_,k)=>vars[k]||'').split('\n').map(line=>line.replace(/\s+\|\s+(?=\||$)/g,'').replace(/\|\s*\|/g,'|').replace(/[ \t]{2,}/g,' ').trim()).join('\n').trim()}
  function build(template,facts,approvedFeatures,userName){const pieces=[];for(const block of (template.blocks||[])){if(block.enabled===false)continue;const em=block.useEmojis!==false;const title=block.title||DescriptionTemplates.BLOCK_LABELS[block.type]||'';const heading=(emoji,label)=>`${em?emoji+' ':''}${label}`.trim();if(block.type==='headline'){const line=replaceVars(block.config?.pattern||'{{YEAR}} {{MAKE}} {{MODEL}} | {{ODOMETER}}',facts,userName);if(line)pieces.push(line)}else if(block.type==='details'){const rows=[];const selected=block.config?.fields||['year','makeModel','drivetrain','odometer','vin','stock'];const add=(key,emoji,label,val)=>{if(selected.includes(key)&&val)rows.push(`${em?emoji+' ':''}${label}: ${val}`)};add('year','🚗','Year',facts.year);add('makeModel','🚘','Make / Model',makeModelLabel(facts.make,facts.model));add('drivetrain','⚙️','Drivetrain',facts.drivetrain);add('odometer','📏','Odometer',facts.odometer);add('vin','🆔','VIN',facts.vin);add('stock','🔢','STK',facts.stock);if(rows.length)pieces.push(`${heading('📊',title)}\n${rows.join('\n')}`)}else if(block.type==='overview'){const ov=conciseOverview(facts.overviewSource,facts,block.config?.sentences||3);if(ov)pieces.push(`${heading('📁',title)}\n${ov}`)}else if(block.type==='features'){const lim=Math.max(1,+block.config?.limit||30),list=approvedFeatures.slice(0,lim).map(x=>`• ${x.label}`);if(list.length)pieces.push(`${heading('🔹',title)}\n${list.join('\n')}`)}else if(block.type==='topFeatures'){const list=topFeatures(facts,approvedFeatures,block.config?.count||5).map(x=>`${em?'⭐ ':'• '}${x.label}`);if(list.length)pieces.push(`${em?'':title?title+'\n':''}${em?'': ''}${list.join('\n')}`)}else if(block.type==='price'){const body=replaceVars(block.config?.text||'{{PRICE}} + GST',facts,userName);if(body)pieces.push(`${heading('💲',title)}\n${body}`)}else if(block.type==='financing'){let body=replaceVars(block.config?.text||'',facts,userName);if(body){body=body.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>em&&!/^[✔•-]/.test(x)?`✔ ${x}`:x).join('\n');pieces.push(`${heading('💳',title)}\n${body}`)}}else if(block.type==='signature'||block.type==='custom'){const body=replaceVars(block.config?.text||'',facts,userName);if(body)pieces.push(body)}}return pieces.filter(Boolean).join('\n\n').trim()}
  async function inspect(vehicle,draft,onProgress=()=>{}){let web=null,error='';if(vehicle?.originalListingUrl){try{onProgress('Checking the Vehicle Profile website for current facts…');web=await WebsiteInfo.scanFacts(vehicle.originalListingUrl,onProgress,vehicle)}catch(e){error=e.message||String(e)}}const supplement=parseSupplementary(web?.rawText||'',vehicle||{});const websitePrice=web?.fields?.price?.value?Number(web.fields.price.value):null,profilePrice=vehicle?.price!==''&&vehicle?.price!=null?Number(vehicle.price):draft.price!==''&&draft.price!=null?Number(draft.price):null;const discrepancies=[];if(websitePrice!=null&&profilePrice!=null&&Number.isFinite(websitePrice)&&Number.isFinite(profilePrice)&&websitePrice!==profilePrice)discrepancies.push(`Website currently shows ${money(websitePrice)}, while this Listing / Vehicle Profile shows ${money(profilePrice)}. LotKeys will keep the Profile price. Check the website and update the Vehicle Profile later if the change is correct.`);const facts={year:String(vehicle?.year||draft.year||''),make:String(vehicle?.make||draft.make||''),model:String(vehicle?.model||draft.model||''),price:money(profilePrice),priceValue:profilePrice??'',odometer:odo(vehicle?.odometer!==''&&vehicle?.odometer!=null?vehicle.odometer:draft.odometer,vehicle?.odometerUnit||draft.odometerUnit||'KM'),odometerValue:vehicle?.odometer!==''&&vehicle?.odometer!=null?vehicle.odometer:(draft.odometer??''),vin:String(vehicle?.vin||''),stock:String(vehicle?.stock||''),engine:supplement.engine,hp:supplement.hp,engineHp:[supplement.hp,supplement.engine].filter(Boolean).join(' ').trim(),drivetrain:supplement.drivetrain,transmission:supplement.transmission,vehicleClass:supplement.vehicleClass||'Vehicle',overviewSource:String(vehicle?.description||web?.fields?.description?.value||''),websiteUrl:vehicle?.originalListingUrl||'',websiteError:error};return{facts,features:supplement.features||[],discrepancies,website:web,error}}
  return{inspect,build};
})();
